* 对方作加倍

** 在二阶水平上的花色应叫都是自然叫，表示是弱牌并有5张套

包括 2c 表示有5张或以上草花，而不是斯泰曼约定叫

** 再加倍

如果有6大牌点或以上，应叫作再加倍，因为你方牌力比对方牌力强，绝大多数情况下可以打成1NT定约；

假如对方逃叫二阶水平某花色，你方可作惩罚性加倍。

在加倍后跳叫三阶水平某花色表示持有5—7大牌点和6张或以上长套。在将牌配合并有高限牌力时，开叫者可进一步叫牌。持有二个长套的畸形牌型有机会成局得分、比作惩罚性加倍罚分更合算时，可以在加倍后叫2NT。以后的叫牌是自然叫，显示自己的花色，直至联手找到最佳定约为止。

* 对方作自然叫进行干扰，例如1NT:(2D)

- 在二阶水平上作花色应叫是竞叫性的，但不是逼叫，牌力约为4—7点。同伴可在该花色中配合并有高限牌力时，加叫同伴的应叫花色。

- 应叫花色低于对方花色时，在三阶水平上作花色应叫不是逼叫。例如，1NT:(2):3。

- 跳叫新花色至三阶水平是逼叫。例如，1NT:(2):3是逼叫，表示在该花色中有5张套。

- 跳叫成局同正常的1NT开叫后的跳叫成局。跳叫3NT不保证在对方花色中有止张。一般情况下，对方长套不大会是坚强长套（否则，对方可以不叫，而利用其坚强长套成功地防守你方的无将定约）。虽然不能肯定，但有理由相信在开叫者手中有对方花色中的止张，因此即使你自己没有止张，也不要怕叫3NT。

- 加倍是惩罚性加倍。持有不少于6大牌点和在对方花色中有好的4张套时，赶快加倍。

- 2NT仍和正常叫法相同是邀请叫。应叫2NT也不一定要保证在对方花色中有止张。

- 叫对方花色是斯泰曼约定叫，逼叫成局。例如，1NT:(2):3保证有4张黑桃，1NT:(2):3保证有4张红心，1NT:(2):3或1NT:(2):3保证至少在一门高级花色中有4张或以上。1NT:(2):加倍是惩罚性加倍而不是斯泰曼约定叫。如果对方争叫低级花色，例如1NT:(2):3:(不叫)，开叫者没有4张高级花色套时叫3NT，同时有二个4张高级花色时叫3，只有一个4张高级花色套时叫该高级花色。在3后，应叫者有支持时加叫至4，或在有4张黑桃时再叫3NT。在3NT后，开叫者有4张黑桃时再叫4或在黑桃较少时不叫。应叫者叫对方花色表示有4张或以上高级花色套，再叫3NT排除红心，所以必有4张黑桃。

* 对方作花色虚叫进行干扰

- 加倍是惩罚性加倍，表示要对该虚叫实际表示的花色作惩罚性加倍。

- 扣叫虚叫花色是自然叫，不是逼叫。例如，1NT:(2—转移叫):3表示持有方块长套，而不是斯泰曼约定叫。表示在该花色中有5张或以上套而且有5—7大牌点。如果对方的花色争叫是自然叫，扣叫该花色是虚叫性约定叫；如果对方的花色争叫是虚叫，扣叫该花色是自然叫。

- 叫出对方虚叫实际表示的花色是代替斯泰曼约定叫的虚叫，而且是成局逼叫。例如，在1NT:(2)后，如果2表示有红心套和一个低级花色套，你叫2是虚叫，起到斯泰曼约定叫的作用。

- 其他叫法和自然争叫后的叫法相同。

